format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_9X60_Evaluation_Kit, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '148', y: '9', id: BSP_SAM_9X60_Evaluation_Kit}
