format_version: v1.0
type: UniqueComponent
attributes: {id: core_timer}
children:
- type: Symbols
  children:
  - type: Float
    attributes: {id: CORE_TIMER_COMPARE_MS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: CORE_TIMER_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '60000000'}
  - type: Comment
    attributes: {id: CORE_TIMER_FREQUENCY_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** Core Timer Clock Frequency 60000000 Hz ***'}
  - type: Boolean
    attributes: {id: CORE_TIMER_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: 'true'}
  - type: Boolean
    attributes: {id: CORE_TIMER_PERIODIC_INTERRUPT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: 'false'}
  - type: Float
    attributes: {id: CORE_TIMER_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '71582.79'}
  - type: Integer
    attributes: {id: CORE_TIMER_PERIOD_US}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '1000'}
  - type: String
    attributes: {id: CORE_TIMER_PERIOD_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '0xea60'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: CORE_TIMER_TMR}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_time}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_time_TMR_dependency}
- type: ElementPosition
  attributes: {x: '111', y: '274', id: core_timer}
