configName: pic32mk_gp_db_freertos
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MK1024GPE100
projectName: ''
settings:
  PackageFilter: bsp;core;csp;csp_apps_pic32mk;quick_docs;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-GP_DFP\1.4.117\atdf\PIC32MK1024GPE100.atdf
