format_version: v1.0
type: UniqueComponent
attributes: {id: usb_host_msd}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CONFIG_USB_HOST_MSD_NUMBER_OF_INSTANCES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: USB Host MSD}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_fs}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_fs_DRV_MEDIA_dependency}
- type: ElementPosition
  attributes: {x: '319', y: '317', id: usb_host_msd}
